apiVersion: v1
kind: Service
metadata:
  name: uptime-kuma-proxy
spec:
  type: ExternalName
  externalName: uptime-kuma.uptime-kuma.svc.cluster.local
  ports:
    - port: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-kuma
  annotations:
    konghq.com/strip-path: "false"
spec:
  ingressClassName: kong
  rules:
    - host: uptime.79.137.54.150.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-kuma-proxy
                port:
                  number: 3001
