replicaCount: 1

image:
  repository: ghcr.io/jrebt/event-logger
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  host: events.51.255.12.10.nip.io

nats:
  url: nats://nats.nats.svc.cluster.local:4222

keda:
  enabled: true
  desiredReplicas: "1"
  timezone: "Europe/Madrid"
  nats:
    enabled: true
    monitoringEndpoint: "nats.nats.svc.cluster.local:8222"
    stream: "EVENTS"
    consumer: "event-logger"
    lagThreshold: "10"
    activationLagThreshold: "5"
    pollingInterval: 5
    cooldownPeriod: 30
    minReplicas: 1
    maxReplicas: 5

resources:
  requests:
    cpu: 25m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi
